### ISSUE TITLE
Integrate Godot's print and Nim's echo

### ISSUE THREAD

**Issue by panno8M** [godot-nim/godot#6]

**Comment by insomniacUNDERSCORElemon** [comment]
This seems like it isn't completed.
`print("pause/unpause")`
Result: `[1] proc print(arg1: Variant; args: varargs[Variant]): void`

echo still gives ambiguous call.

Maybe you should use a new name? I think gecho (said like gecko or g-echo) would work, or gprint. 

Also just to be clear, am I right in thinking that this has a small area of utility? It seems like the only time echo would work during building would be conditionless (or `likely(true)`) top-level code and maybe ready(). At least I imagine Godot's print would already print to terminal just fine, so the value of this would be if the code can run through Nim _without_ Godot.

**Comment by panno8M** [comment]
It was intended to be used as `system.echo ...` and `godot.echo ...`.
Change to a form that allows any type to be passed to godot.print and remove the current `echo(varargs[Variant, variant])`.

Note:
Exactly the print function does not work at the top level or within functions called from the top level. (This is because there is an internal process to get the function pointer to print from the godot runtime.)

**Comment by insomniacUNDERSCORElemon** [comment]
> It was intended to be used as `system.echo ...` and `godot.echo ...`.

Alright both of those work.

For the note, I guess I was overthinking it as it looks like system.echo only shows up in the terminal (running with `godot --editor`) whereas the other is there plus in Godot's output.
