### ISSUE TITLE
is it possible to have a custom icon for classes?

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/godot#9]
For this project, instead of the node icon that is.

I made a 32x32 mockup:

![icon_test](https://github.com/user-attachments/assets/3ae6b8bd-6ee8-42de-9a4a-ac59e361dce8)

Though using the actual\* node icon with an additional overlay (a yellow-dotted circle, like a crown from above) would be even better, and that could possibly be easy enough to use/adapt the same format (svg) as Godot's node icons already use.

\*=currently, if you have a class that uses Control, it still uses the standard node icon rather than the control icon.

EDIT: Actually I don't think my mockup with a node circle icon over it looks too bad:
![crown_overlay](https://github.com/user-attachments/assets/8daf6e7d-3688-4ba1-88f0-b9545c04203e)

 though it would look better shifted up with the other shifted down.

Or:  ![small_crown](https://github.com/user-attachments/assets/bd0466ea-aa2b-4547-8709-2e633f3ea098)

-----------------------

On the note of integration, is there anything else you can do in the editor? Like a dedicated abstract base class (rather than mixed in) plus allowing custom groupings for that (when registering the class) as well... that's still a different workflow than scripts (which I hope can be attached in the editor, with filling in imports/ready/signals\*\* etc), but [a video on component-based design](https://www.youtube.com/watch?v=rCu8vQrdDDI) is the first bookmark in my godot bookmarks so I can certainly see the appeal.

I suppose it would be simple enough to just have a message in Godot's output.  `4 classes successfully loaded, 1 used in current scene` or something like that. 0 classes loaded would make it clear it's not loaded, and a message could further point to node usage.

\*\*=EDIT: connecting signals via the editor does work now, it just needs to be done via a dummy script ~~(which can be deleted after, but doing so will add some annoyance to renaming)~~ this seems finicky, or very possibly I made some other mistake. The 3.X version having a script placeholder made it not have this issue.

**Comment by insomniacUNDERSCORElemon** [comment]
Slightly different thing: it'd be nice to remove the leading underscores out of signal names that way you don't need to rename via pragmas. Though manually editing the signal name in the editor does do this.

I don't know what type of issues this might cause though (particularly when other languages are used). Though it could be a setting/plugin, or perhaps just a shorter pragma like `prefix: "_" `

**Comment by panno8M** [comment]
### About custom icons

You can manually.

```diff
# decbinhex.gdextension
+ [icons]
+ Main = "res://path/to/icon"
```

I will add it to the task list for #8 .
(Since I have to start with learning the svg library, this is a little lower priority.)

reference: [The godot-rust Book - Custom node icons](https://godot-rust.github.io/book/recipes/custom-icons.html)

**Comment by panno8M** [comment]
> Slightly different thing: it'd be nice to remove the leading underscores out of signal names that way you don't need to rename via pragmas. Though manually editing the signal name in the editor allows this.
> 
> I don't know what type of issues this might cause though (particularly when other languages are used). Though it could be a setting/plugin, or perhaps just a shorter (and non-unique) pragma like `prefix: "_" `

Since calls to functions registered with Godot are made by specifying the name with StringName (and the Godot side will request execution of the function by specifying the name with StringName), there is no need to worry about coexistence with other languages in that regard.

It may be useful to support formattor in the name pragma.
For example, `{.name:“_{procname: lower_snake}”.} `
